[package]
name = "stdlib"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
fastnum = "0.7.0"
macros = { path = "../macros" }

[dev-dependencies]
macrotest = "1.2"
trybuild = "1.0"
