[workspace]
members = ["consensus-sim", "indexer", "indexer-types", "macros", "stdlib", "testlib", "wit-validator"]
resolver = "2"

[workspace.lints.clippy]
new_without_default = "allow"
uninlined_format_args = "allow"
too_many_arguments = "allow"

[workspace.dependencies]
# IMPORTANT
wasmtime = { version = "=41.0.3", features = ["wave", "component-model-async"] }
wit-bindgen = "=0.53.0"
wit-component = "=0.245.1"
wit-parser = "=0.245.1"
wasm-wave = { version ="0.245.1", default-features = false }

anyhow = { version = "=1.0.101", default-features = false }
async-trait = "=0.1.89"
axum = { version = "=0.8.8", features = ["http2", "ws"] }
bitcoin = { version = "=0.32.8", features = ["serde", "rand", "rand-std"] }
bon = { version = "=3.8.2", default-features = false, features = ["alloc"] }
bytes = "=1.11.1"
clap = { version = "=4.5.58", features = ["derive"] }
eyre = "=0.6.12"
glob = "=0.3.3"
indexmap = { version = "=2.13.0", features = ["serde"] }
libsql = "=0.9.29"
postcard = { version = "1.1.3", default-features = false, features = ["alloc"] }
prost = "=0.13.5"
serial_test = "=3.3.1"
serde = { version = "=1.0.228", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "=1.0.149", default-features = false, features = ["alloc"] }
serde_with = { version = "=3.16.1", default-features = false, features = ["alloc", "macros"] }
sha3 = "=0.10.8"
tempfile = "=3.25.0"
tokio = { version = "=1.49.0", features = ["full"] }
tower = "=0.5.3"
tower-http = { version = "=0.6.8", features = [
  "fs",
  "trace",
  "compression-full",
  "request-id",
  "timeout",
  "catch-panic",
  "cors",
] }
tracing = "=0.1.44"
tracing-subscriber = { version = "=0.3.22", features = ["env-filter"] }
ts-rs = { version = "=12.0.1", features = ["format"] }

# Malachite BFT consensus
malachitebft-app-channel = { git = "https://github.com/circlefin/malachite", package = "informalsystems-malachitebft-app-channel" }
