[package]
name = "consensus-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
indexer = { path = "../indexer" }
malachitebft-app-channel = { git = "https://github.com/circlefin/malachite", package = "informalsystems-malachitebft-app-channel" }

clap = { version = "4.5", features = ["derive"] }
eyre = "0.6"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
tempfile = "3"
